defaults:
  - finetune # Inherits base training arguments like learning_rate, batch_size, etc.

handler: GeometricUnlearn

args: # HuggingFace TrainingArguments
  learning_rate: 1e-5
  num_train_epochs: 5
  max_steps: -1
  optim: adamw_torch
  adam_beta1: 0.0
  weight_decay: 0.0
  fp16: false
  bf16: false
  bf16_full_eval: false
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false

method_args:
  alpha: 1.0
  gamma: 1.5
  retain_loss_type: NLL
  geometric_config:
    loss: "simnpo"
    gu_enabled: true
    projection_eps: 1.0e-12
    sign_selective: false
    trainable_params_regex: 
      - ".*"

  # all other config options are inherited from SimNPO
  simnpo_config:
    delta: 0.0 # gamma in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
    beta: 4.5
    alpha: 1.0
    gamma: 0.125 # npo_coeff in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
    retain_loss_type: NLL

  npo_config:
    beta: 0.1
    alpha: 1.0
    gamma: 1.0
    retain_loss_type: NLL

  dpo_config:
    beta: 0.1
    alpha: 1.0
    gamma: 1.0
    retain_loss_type: NLL

  undial_config:
    gamma: 1.0
    alpha: 0.0
    beta: 10.0 # the strength of penalty for memorized tokens
    retain_loss_type: NLL 

  satimp_config:
    beta1: 5.0
    beta2: 1.0
    alpha: 1.0
    gamma: 0.1
    retain_loss_type: NLL

  wga_config:
    beta: 1.0
    alpha: 1.0
    gamma: 1.0
    retain_loss_type: NLL
