# @package eval.muse.metrics.retain_extraction_strength
# 上述 @package 声明确保此配置在Hydra中被正确加载和组织

# 默认配置继承
defaults:
  # 继承通用的数据整理器（collator）配置
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

# 指定处理逻辑的handler
handler: extraction_strength

# 从全局评估配置中获取batch_size变量
batch_size: 8

# 数据集特定配置
datasets:
  MUSE_retain_knowmem:
    handler: QADataset
    args:
      hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
        name: "knowmem"
        split: "retain_qa"
      few_shot_dataset_hf_args:
        path: muse-bench/MUSE-${eval.muse.data_split}
        name: "knowmem"
        split: "retain_qa_icl"
      question_key: "question"
      answer_key: "answer"
      max_length: 512
